#!/bin/bash
set -e

case "$1" in
	reconfigure)
		a2dissite "010-bankapi"
		;;&
	configure|reconfigure)
		if [ ! -e "/etc/apache2/sites-enabled/010-bankapi.conf" ]; then
			a2ensite -q "010-bankapi"
			a2enmod -q cgi
			service apache2 restart
		fi
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		# We don't have to do anything because we didn't do anything in prerm
		exit 0
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
